# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c45ce81cae89e8211e3383e78350e7e42173840d1689b8fd68088d23d3890f8ce1df1e97090b2a88267993654e8e610a02e94dcb962307ce2fb56fd74e5a6afe

test:
  secret_key_base: cf94292e21d646ceb81fe7b2a7f5ab3f690fc76c94e957fc267a70eca45fbe2df201f6c376e1d13e6c90d84d9d312b059bcef863aa16beccc3fe6f9985b4f055

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
